#!/usr/bin/env python3
"""Generate inkplate/firmware/fortunes/fortunes_data.h from BSD fortune files.

Reads /usr/share/games/fortunes/{fortunes,literature,riddles} (Debian
package: fortunes-min, BSD-4-clause with the advertising clause rescinded
per the 1999 Berkeley letter — see NOTICE). Each `%`-delimited entry is
ASCII-folded (NFKD then ASCII-encode-ignore, matching the
external_display normalization pipeline), has its whitespace collapsed
to single spaces, and is kept only if it ends up short enough to display
comfortably on the Inkplate panel.

Re-run after editing this script or after the source corpus changes;
commit the regenerated header.
"""
from __future__ import annotations

import json
import re
import sys
import unicodedata
from pathlib import Path


# Source files. fortunes-min is preferred over the full fortunes package
# because the curated set is smaller and uniformly cleared for Debian main.
SRC_FILES = [
    Path("/usr/share/games/fortunes/fortunes"),
    Path("/usr/share/games/fortunes/literature"),
    Path("/usr/share/games/fortunes/riddles"),
]

# Length cap. drawTextBox at size=3 in an 800x600 panel with 40 px margins
# fits roughly ~50 chars per line and ~10 lines; 120 chars leaves comfortable
# room for two wrapped lines without dominating the screen.
MAX_LEN = 120

# Minimum word count. Single-token entries are usually leftover headers
# (e.g. "Knock, knock!") from multi-line items the parser fragmented.
MIN_WORDS = 3

# Output header file, relative to this script's parent dir.
OUT = Path(__file__).resolve().parent.parent / "fortunes" / "fortunes_data.h"

_WS_RE = re.compile(r"\s+")


def normalize(s: str) -> str:
    """NFKD + ASCII fold + whitespace collapse. Same pipeline as
    external_display._normalize_text; kept independent to avoid coupling
    a build-time corpus generator to runtime server code."""
    s = unicodedata.normalize("NFKD", s).encode("ascii", errors="ignore").decode("ascii")
    s = _WS_RE.sub(" ", s).strip()
    return s


def extract(path: Path) -> list[str]:
    """Split a fortune file on `\\n%\\n` (the canonical separator in
    fortune-mod data files), normalize each entry, filter."""
    if not path.is_file():
        print(f"warning: {path} not found, skipping", file=sys.stderr)
        return []
    text = path.read_text(encoding="utf-8", errors="replace")
    out: list[str] = []
    for chunk in text.split("\n%\n"):
        chunk = chunk.strip()
        if not chunk:
            continue
        norm = normalize(chunk)
        if not norm:
            continue
        if len(norm) > MAX_LEN:
            continue
        if len(norm.split()) < MIN_WORDS:
            continue
        out.append(norm)
    return out


def main() -> int:
    collected: list[str] = []
    for src in SRC_FILES:
        items = extract(src)
        print(f"  {src.name}: kept {len(items)} fortunes", file=sys.stderr)
        collected.extend(items)

    # Dedupe preserving the first occurrence, then sort for stable output.
    seen: set[str] = set()
    unique: list[str] = []
    for f in collected:
        if f not in seen:
            seen.add(f)
            unique.append(f)
    unique.sort()

    if not unique:
        print("error: no fortunes collected", file=sys.stderr)
        return 1

    # Emit header. JSON-encode each string for safe escaping into a C++
    # string literal — JSON's string syntax is a subset of C/C++'s.
    lines = [
        "// Auto-generated by inkplate/firmware/tools/build_fortunes.py.",
        "// DO NOT EDIT BY HAND — re-run the script and commit the result.",
        "//",
        "// Source corpus: /usr/share/games/fortunes/{fortunes,literature,riddles}",
        "// (Debian fortunes-min package, BSD-4-clause with the advertising clause",
        "// rescinded per the Berkeley 1999 letter; see NOTICE for the full",
        "// attribution).",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        f"constexpr size_t FORTUNES_COUNT = {len(unique)};",
        "",
        "const char* const FORTUNES[FORTUNES_COUNT] = {",
    ]
    for f in unique:
        lines.append(f"    {json.dumps(f)},")
    lines.append("};")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(unique)} fortunes to {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
