#pragma once
// Generated by inkplate/tools/fixture-to-smoke-header.sh from
// inkplate/fixtures/normal_bulletin__pinned_first/in.json.
// To regenerate from a different fixture:
//   ./inkplate/tools/fixture-to-smoke-header.sh fixtures/<name>/in.json
//
// No PROGMEM — ESP32's XIP flash mapping makes .rodata directly
// readable by ArduinoJson without the F() macro or Flash reader.
static const char SMOKE_FIXTURE_JSON[] = "{\"envelope\":{\"status\":\"ok\",\"radio_state\":\"ok\",\"portal_state\":\"ok\",\"battery_volts\":3.95,\"seconds_since_last_update\":60,\"active_channel_index\":0,\"failure_reason\":null,\"firmware_version\":\"0.1.0\",\"expected_api_version\":2,\"cached_payload\":null},\"payload\":{\"api_version\":2,\"server_time\":1747431138,\"hub\":{\"site_name\":\"Greenwood Library\",\"callsign\":\"gwd\"},\"channels\":[{\"name\":\"#hub-board\",\"scope\":\"local\",\"messages\":[{\"id\":101,\"ts\":1747430000,\"sender\":\"dispatch\",\"body\":\"Block party Saturday 2pm. Bring chairs.\"},{\"id\":102,\"ts\":1747430800,\"sender\":\"alice\",\"body\":\"Water main spotted in front of 4516.\"},{\"id\":103,\"ts\":1747431100,\"sender\":\"bob\",\"body\":\"On it. Will flag the corner.\"}]}]}}";
