#!/usr/bin/env bash
# Convert a fixture in.json into firmware/bulletin/smoke_fixture.h.
#
# Usage: fixture-to-smoke-header.sh path/to/fixture/in.json
# Output: inkplate/firmware/bulletin/smoke_fixture.h (overwritten)
#
# The output is a plain `static const char[]` — NOT marked PROGMEM.
# On ESP32, .rodata is XIP-mapped and dereferenceable via a normal
# `const char*`, so ArduinoJson can deserialize it directly without
# the F() macro or the FlashReader specialization. Marking it
# PROGMEM would either silently work (because ESP32's PROGMEM is
# effectively a section attribute) or route ArduinoJson through the
# wrong Reader path. Don't qualify; just use .rodata.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <fixture-in.json>" >&2
    exit 2
fi
IN="$1"
[ -f "$IN" ] || { echo "ERROR: $IN not found" >&2; exit 1; }

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/inkplate/firmware/bulletin/smoke_fixture.h"
ABS_IN="$(cd "$(dirname "$IN")" && pwd)/$(basename "$IN")"
REL="${ABS_IN#$ROOT/}"

mkdir -p "$(dirname "$OUT")"

python3 - "$ABS_IN" "$REL" > "$OUT" <<'PY'
import json, sys
src_path = sys.argv[1]
rel_path = sys.argv[2]
data = json.loads(open(src_path).read())
compact = json.dumps(data, separators=(",", ":"))
escaped = compact.replace("\\", "\\\\").replace("\"", "\\\"")
print("#pragma once")
print(f"// Generated by inkplate/tools/fixture-to-smoke-header.sh from")
print(f"// {rel_path}.")
print("// To regenerate from a different fixture:")
print("//   ./inkplate/tools/fixture-to-smoke-header.sh fixtures/<name>/in.json")
print("//")
print("// No PROGMEM — ESP32's XIP flash mapping makes .rodata directly")
print("// readable by ArduinoJson without the F() macro or Flash reader.")
print(f"static const char SMOKE_FIXTURE_JSON[] = \"{escaped}\";")
PY

echo "wrote $OUT (from $REL)" >&2
